AWSTemplateFormatVersion: "2010-09-09"
Description: >
  LKS Serverless Order Processing Architecture
  (Lambda Only, Inline Code, AWS Learner Lab Compatible)

Parameters:
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnets for Order Management Lambda

  LambdaSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group for Lambda in VPC

  RdsEndpoint:
    Type: String
    Description: RDS Endpoint

  DbName:
    Type: String
  DbUsername:
    Type: String
  DbPassword:
    Type: String
    NoEcho: true

  OrderBucketName:
    Type: String
    Description: S3 Bucket for order data

  StepFunctionArn:
    Type: String
    Description: Step Functions State Machine ARN

Resources:

  ########################################
  # 1. Order Management Lambda (VPC)
  ########################################
  OrderManagementLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-order-management
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      MemorySize: 512
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds: !Ref PrivateSubnetIds
      Environment:
        Variables:
          RDS_ENDPOINT: !Ref RdsEndpoint
          DB_NAME: !Ref DbName
          DB_USERNAME: !Ref DbUsername
          DB_PASSWORD: !Ref DbPassword
          ORDER_BUCKET: !Ref OrderBucketName
          STEP_FUNCTION_ARN: !Ref StepFunctionArn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  "statusCode": 200,
                  "service": "Order Management",
                  "message": "Order processed successfully",
                  "input": event
              }

  ########################################
  # 2. Process Payment Lambda
  ########################################
  ProcessPaymentLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-process-payment
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      MemorySize: 512
      Timeout: 30
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  "statusCode": 200,
                  "service": "Process Payment",
                  "message": "Payment processed",
                  "order_id": event.get("order_id")
              }

  ########################################
  # 3. Update Inventory Lambda
  ########################################
  UpdateInventoryLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-update-inventory
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      MemorySize: 256
      Timeout: 45
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  "statusCode": 200,
                  "service": "Update Inventory",
                  "message": "Inventory updated",
                  "product_id": event.get("product_id")
              }

  ########################################
  # 4. Send Notification Lambda
  ########################################
  SendNotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-send-notification
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      MemorySize: 256
      Timeout: 60
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  "statusCode": 200,
                  "service": "Send Notification",
                  "message": "Notification sent",
                  "target": event.get("email", "customer")
              }

  ########################################
  # 5. Generate Report Lambda
  ########################################
  GenerateReportLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-generate-report
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      MemorySize: 1024
      Timeout: 60
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              report_type = event.get("type", "summary")
              return {
                  "statusCode": 200,
                  "service": "Generate Report",
                  "report_type": report_type,
                  "message": "Report generated successfully"
              }

  ########################################
  # 6. Init Database Lambda
  ########################################
  InitDatabaseLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-init-db
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          RDS_ENDPOINT: !Ref RdsEndpoint
          DB_NAME: !Ref DbName
          DB_USERNAME: !Ref DbUsername
          DB_PASSWORD: !Ref DbPassword
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {
                  "statusCode": 200,
                  "service": "Init Database",
                  "message": "Database initialized (schema, tables, indexes)"
              }

Outputs:
  OrderManagementLambdaArn:
    Description: Order Management Lambda ARN
    Value: !GetAtt OrderManagementLambda.Arn

  ProcessPaymentLambdaArn:
    Description: Process Payment Lambda ARN
    Value: !GetAtt ProcessPaymentLambda.Arn

  UpdateInventoryLambdaArn:
    Description: Update Inventory Lambda ARN
    Value: !GetAtt UpdateInventoryLambda.Arn

  SendNotificationLambdaArn:
    Description: Send Notification Lambda ARN
    Value: !GetAtt SendNotificationLambda.Arn

  GenerateReportLambdaArn:
    Description: Generate Report Lambda ARN
    Value: !GetAtt GenerateReportLambda.Arn

  InitDatabaseLambdaArn:
    Description: Init Database Lambda ARN
    Value: !GetAtt InitDatabaseLambda.Arn
